# Force GitHub to recognize this as a Python repository
languages:
  Python: true

# Mark ALL non-Python files as vendored (completely exclude from language stats)
vendored:
  - "*.mp4"
  - "*.png"
  - "*.jpg"
  - "*.jpeg"
  - "*.webp"
  - "*.pkl"
  - "*.h5"
  - "*.bin"
  - "*.html"
  - "*.css"
  - "*.js"
  - "*.md"
  - "*.txt"
  - "templates/"
  - "static/"

# Mark specific directories as vendored
vendored_directories:
  - "templates"
  - "static"
  - "venv"
  - ".venv"
