# Force GitHub to recognize this as a Python repository
languages:
  Python: true

# Mark all non-Python files as vendored or documentation
vendored:
  - "*.mp4"
  - "*.png"
  - "*.jpg"
  - "*.jpeg"
  - "*.webp"
  - "*.pkl"
  - "*.h5"
  - "*.bin"
  - "*.html"
  - "*.css"
  - "*.js"

# Mark documentation files
documentation:
  - "*.md"
  - "*.txt"
  - "*.html"
  - "*.css"
  - "*.js"
